config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :following, :followers, :mypage, :favorite
    end
  end

  resources :pictures do
    collection do
      get :tomorrow_index
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  require 'jp_prefecture'

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, length: { in: 1..10 }
  validates :email, presence: true
  validates :gender, presence: true
  validates :prefecture_code, presence: true
  validates :icon, presence: true

  enum gender: { man:1, woman:2 }

  include JpPrefecture
  jp_prefecture :prefecture

  mount_uploader :icon, IconUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :notify_new_record

  def notify_new_record
    NewuserMailer.hello(self).deliver_now
  end

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

   #before_action :configure_sign_up_params, only: [:create]
   #before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   #def new
    # super
  # end

  # POST /resource
  #def create
  #  super
  #Send
  # GET /resource/edit
  # def edit
    # super
   ##end

  # PUT /resource
   #def update
     #super
   #end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   #protected

  # If you have extra params to permit, append them to the sanitizer.
   #def configure_sign_up_params
     #devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :icon])
   #end

  # If you have extra params to permit, append them to the sanitizer.
   #def configure_account_update_params
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name, :icon])
   #end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show, :following, :followerd, :mypage, :favorite]
  # after_create :notify_new_record
  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures.page(params[:page]).per(20).order('created_at DESC')
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end

  def mypage
    @user = current_user
    @pictures = @user.pictures.page(params[:page]).per(20).order('created_at DESC')
  end

  def favorite
    @user = current_user
    @pictures = @user.favorite_pictures.page(params[:page]).per(20).order('created_at DESC')
  end

  private

  def user_check
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to pictures_path, notice:"投稿者以外は編集できません"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build(followed_id: @user.id))  do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "フォロー", class: "white_button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
<% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "white_button" %>
<% end %>

app/views/users/favorite.html.erb
<div class = "center">
  <h1 class = "title"><%= @user.name %>さんのお気に入り一覧</h1>

  <% @pictures.each do |picture| %>
    <div class="panel-body">
      <%= link_to image_tag(picture.image.url), picture_path(picture.id) %><br>
    </div>
  <% end %>
  <% if @user == current_user %>
    <%= link_to "マイページへ", mypage_user_path(current_user), class:"button_while" %>
  <% else %>
    <%= link_to "もどる", user_path(@user.id), class:"button_while"%>
  <%end %>
  <%= paginate @pictures %>
</div>

app/views/users/followers.html.erb
<div class = "center">
  <h1 class = "title"><%= @user.name %>さんのフォロワー一覧</h1>
  <% @users.each do |user| %>
    <div class = "users">
      <div class = "user icon_between"><%= image_tag user.icon.url, class:"icon" %></div>
      <% if user == current_user %>
        <h4 class = "user"><%= link_to user.name, mypage_user_path(current_user) %></h4><br>
      <% else %>
        <h4 class = "user"><%= link_to user.name, user_path(user.id) %></h4><br>
      <% end %>
    </div>
  <% end %>
  <div class = "button-top-padding">
  <% if @user == current_user %>
      <%= link_to "もどる", mypage_user_path(current_user) , class:"button_while"%>
    <% else %>
      <%= link_to "もどる", user_path(@user.id) , class:"button_while"%>
    <%end %>
  </div>
</div>

app/views/users/following.html.erb
<div class = "center">
  <h1 class = "title"><%= @user.name %>さんのフォロー一覧</h1>

  <% @users.each do |user| %>
  <div class = "users">
    <div class = "user icon_between"><%= image_tag user.icon.url, class:"icon" %></div>
    <% if user == current_user %>
      <h4 class = "user"><%= link_to user.name, mypage_user_path(current_user) %></h4><br>
    <% else %>
      <h4 class = "user"><%= link_to user.name, user_path(user.id) %></h4><br>
    <% end %>
  </div>
  <% end %>

  <div class = "button-top-padding">
    <% if @user == current_user %>
      <%= link_to "もどる", mypage_user_path(current_user), class:"button_while"%>
    <% else %>
      <%= link_to "もどる", user_path(@user.id), class:"button_while"%>
    <%end %>
  </div>
</div>

app/views/users/mypage.html.erb
<div class = "center">
  <h1 class = "title"><%= @user.name %>さんのマイページ</h1>
    <div class = "users">
      <div class = "icon_between"><%= image_tag @user.icon.url, class:"icon" %></div><br>
      <% @user ||= current_user %>
        <div class="stats">
          <a href="<%= following_user_path(@user) %>">
          <strong id="following" class="stat">
            <%= @user.following.count %>
          </strong>フォロー
          </a>
          <a href="<%= followers_user_path(@user) %>">
          <strong id="followers" class="stat">
            <%= @user.followers.count %>
          </strong>フォロワー
          </a>
        </div>
    </div>
    <br>
    <div class = "users">
      <%= link_to "お気に入り一覧" , favorite_user_path(@user) ,class:"white_button" %>
      <%= link_to "ユーザー情報編集", edit_user_registration_path ,class:"white_button" %>
    </div>
    <!-- カレンダー表示 -->
    <%= month_calendar events: @pictures do |date, pictures| %>
      <%= date.day %>

      <% pictures.each do |picture| %>
        <div>
          <%= link_to image_tag(picture.image.url, width: "100"), picture_path(picture.id) %>
        </div>
      <% end %>
    <% end %>

  <h2 class = "title">あなたのTENKIHUKU一覧</h2>

  <% @pictures.each do |picture| %>
    <div class="panel-body">
      <%= link_to image_tag(picture.image.url), picture_path(picture.id) %><br>
    </div>
      <% end %>
  <%= paginate @pictures %>

    <script src ="https://api.darksky.net/forecast/b0207e10b3cfa549c07daf016400ada2/35.681167,139.767052"></script>

    <%= link_to '今日の天気へ', pictures_path, class:"button_while" %><br>
</div>

app/views/users/show.html.erb
<div class = "center">
  <h1 class ="title"><%= @user.name %>さんのページ</h1>
    <div class = "users">
      <div class ="icon_between"><%= image_tag @user.icon.url, class:"icon" %></div><br>

      <% @user ||= current_user %>
        <div class="stats icon_between">
          <a href="<%= following_user_path(@user) %>">
          <strong id="following" class="stat">
            <%= @user.following.count %>
          </strong>
            フォロー
          </a>
          <a href="<%= followers_user_path(@user) %>">
            <strong id="followers" class="stat">
              <%= @user.followers.count %>
            </strong>
              フォロワー
          </a>
        </div>

      <% unless @user == current_user %>
        <%= render "follow_form"%>
      <% end %>
    </div>
    <br>

    <h3><%= @user.name %>さんのTENKIHUKU一覧</h3>
    <% @pictures.each do |picture| %>
    <div class="panel-body">
      <%= link_to image_tag(picture.image.url), picture_path(picture.id) %><br>
    </div>
    <% end %>
    <%= paginate @pictures %>
    <br>
    <%= link_to '今日の天気へ', pictures_path, class:"button_while" %><br>
</div>