config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :following, :followers, :mypage, :favorite
    end
  end

  resources :pictures do
    collection do
      get :tomorrow_index
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, length: { maximum: 255 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  enum gender: { man:1, woman:2 }

  def setting_weather_status(temperature)
    case temperature
    when (26..Float::INFINITY) then self.weather = 1
    when (21..25.99) then self.weather = 2
    when (16..20.99) then self.weather = 3
    when (12..15.99) then self.weather = 4
    when (7..11.99) then self.weather = 5
    else self.weather = 6
    end
  end

  def setting_start_time
    self.start_time = Date.today
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
before_action :set_picture, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, :only => [:new, :create, :edit, :show, :update, :destroy, :confirm, :index]
before_action :user_check, only: [:edit, :destroy]

  def new
      @picture = Picture.new
  end

  def create
    prefecture = Prefecture.find(current_user.prefecture_code.to_s)
    apparent_temperature = prefecture.current_temperature
    @picture = current_user.pictures.build(picture_params)
    @picture.setting_weather_status(apparent_temperature)
    @picture.setting_start_time
    if @picture.save
      redirect_to pictures_path, notice: "TENKIHUKUを作成しました"
    else
      render "new"
    end
  end

  def edit
  end

  def index
    @prefecture = Prefecture.find(current_user.prefecture_code.to_s)
    @apparent_temperature = @prefecture.current_temperature
    @weather = @prefecture.today_weather
    @temperature_high = @prefecture.temperature_high
    @temperature_low = @prefecture.temperature_low
    @rain_possibility = @prefecture.rain_possibility
    @pictures = Picture.all
    @pictures = Picture.page(params[:page]).per(20).order('created_at DESC')
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id), notice:"TENKIHUKUを編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"TENKIHUKUを削除しました"
  end

  def tomorrow_index
    @prefecture = Prefecture.find(current_user.prefecture_code.to_s)
    @apparent_temperature = @prefecture.current_temperature
    @weather = @prefecture.today_weather
    @temperature_high = @prefecture.temperature_high
    @temperature_low = @prefecture.temperature_low
    @rain_possibility = @prefecture.rain_possibility
    @pictures = Picture.all
    @pictures = Picture.page(params[:page]).per(20).order('created_at DESC')
  end

  private

  def picture_params
    params.require(:picture).permit(:content, :image, :start_time)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def user_check
    @picture = Picture.find(params[:id])
    unless current_user.id == @picture.user_id
      redirect_to pictures_path, notice:"投稿者以外は編集できません"
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end

  def weather_icon(weather)
    case weather
    when "clear-day" || "clear-night" then image_tag "clear-day.jpeg"
    when "rain" then image_tag "rain.jpeg"
    when "snow" then image_tag "snow.jpeg"
    when "sleed" then image_tag "sleed.jpeg"
    when "wind" then image_tag "wind.jpeg"
    when "fog" then image_tag "fog.jpeg"
    when "cloudy" then image_tag "cloudy.jpeg"
    else image_tag "sunny_cloudy.jpeg"
    end
  end

  def weather_japanese(weather)
    case weather
    when "clear-day" || "clear-night" then @weather = "晴れ"
    when "rain" then @weather = "雨"
    when "snow" then @weather = "雪"
    when "sleed" then @weather = "みぞれ"
    when "wind" then @weather = "強風"
    when "fog" then @weather = "霧"
    when "cloudy" then @weather = "くもり"
    else @weather = "晴れ時々くもり"
    end
  end

  def weather_description(apparent_temperature)
    case apparent_temperature
    when (26..Float::INFINITY) then @weather_description = "暑い！まだまだ半袖が活躍"
    when (21..25.99) then @weather_description = "快適！半袖と長袖の分かれ目"
    when (16..20.99) then @weather_description = "やや肌寒い！重ね着が楽しめる時期"
    when (12..15.99) then @weather_description = "寒さがじわじわ！軽めのアウターを用意しよう"
    when (7..11.99) then @weather_description = "今日は寒い！厚手のコートで出かけよう"
    else @weather_description = "凍える寒さ！防寒対策は万全に"
    end
  end

  def current_pictures(apparent_temperature)
    case apparent_temperature
    when (26..Float::INFINITY) then @current_temperature = 1
    when (21..25.99) then @current_temperature = 2
    when (16..20.99) then @current_temperature = 3
    when (12..15.99) then @current_temperature = 4
    when (7..11.99) then @current_temperature = 5
    else @current_temperature = 6
    end
  end

  def picture_temperure(weather)
    case weather
    when 1 then @temperature = "26℃以上"
    when 2 then @temperature = "21~25℃"
    when 3 then @temperature = "16~20℃"
    when 4 then @temperature = "12~15℃"
    when 5 then @temperature = "7~11℃"
    else @temperature = "6℃以下"
    end
  end
end

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @picture, local: true) do |form| %>
  <div class="image_file">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="TENKIHUKU_content">
    <%= form.label :content %>
    <%= form.text_field :content, :placeholder => "空欄でもOKです!" %>
  </div>
  <%= form.submit "投稿する" %>
<% end %>

app/views/pictures/confirm.html.erb
<div class = "center">
<h3 class = "title">以下の内容で送信する</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= image_tag attachment_url(@picture, :image) %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :start_time %>
  <p><%= @picture.content %></p>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :start_time %>
  <%= form.submit "戻る", name: "back" %>
<% end %>
</div>

app/views/pictures/edit.html.erb
<div class = "center">
  <h1 class = "title">TENKIHUKU編集</h1>
  <%= render "form" %>
</div>

app/views/pictures/index.html.erb
<div class = "center">
  <h1 class = "title">今日の天気<span class = "prefecture_name_size">(<%= @prefecture.name %>)</span></h1>
  <div class = "container">
<div class = "between_weathwe">
    <%= weather_icon(@weather) %>
      <p class = "weather_font"><%= weather_japanese(@weather) %></p>
  </div>
    <div>
      <p class = "weather_top weather_font">体感気温：<%= @apparent_temperature.round %>℃</p>
      <p class = "weather_font">最高気温：<%= @temperature_high.round %>℃</p>
      <p class = "weather_font">最低気温：<%= @temperature_low.round %>℃</p>
      <p class = "weather_font">降水確率：<%= @rain_possibility.round %>%</p>
    </div>
  </div>
    <h4><span class = "under"><%= weather_description(@apparent_temperature) %></span></h4>
    <h2 class = "title">今日のTENKIHUKU一覧</h2>
    <% @pictures.each do |picture| %>
    <% current_pictures(@apparent_temperature) %>
      <% if current_user.gender == picture.user.gender && @current_temperature == picture.weather %>
      <div class="panel-body">
        <%= link_to image_tag(picture.image.url) ,picture_path(picture.id),class:"item" %>
        <br>
      </div>
      <% end %>
    <% end %>
  <%= paginate @pictures %>
  <br>
  <%= link_to 'TENKIHUKUを投稿する', new_picture_path, class:"button_while" %>
</div>

app/views/pictures/new.html.erb
<div class = "center">
  <h1 class = "title">TENKIHUKU新規投稿</h1>
  <%= render "form" %>
</div>

app/views/pictures/show.html.erb
<div class = "center">
  <h1 class = "title">TENKIHUKU詳細</h1>

  <div class = "container users">
    <div class = "user icon_between">
      <%= image_tag @picture.user.icon.url, class: "icon" %>
    </div>
    <% if @picture.user.id == current_user.id %>
      <h4 class = "user"><%= link_to current_user.name, mypage_user_path(current_user) %></h4>
    <% else %>
      <h4 class = "user"><%= link_to @picture.user.name, user_path(@picture.user_id) %></h4>
    <% end %>
  </div>
  <p class = "button-top-padding"><%= image_tag @picture.image.url %></p>
  <p><%= @picture.content %></p>
  <p><%= "投稿日：#{@picture.created_at.strftime('%Y/%m/%d')}" %></p>
  <p><%= "体感気温：#{picture_temperure(@picture.weather)}" %></p>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'white_button' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'white_button' %>
    <% end %>
  <% end %>
  <% if @picture.user.id == current_user.id %>
    <%= link_to '編集', edit_picture_path(@picture.id) %>
    <%= link_to '削除', picture_path(@picture.id), method: :delete, data: {confirm: "本当に削除していいですか？"} %>
  <% end %>
  <br>
  <div class = "button-top-padding">
    <%= link_to '今日の天気へ', pictures_path , class:"button_while" %>
  </div>
</div>

app/views/pictures/tomorrow_index.html.erb
<div class = "center">
  <h1 class = "title">明日の天気<span class = "prefecture_name_size">(<%= @prefecture.name %>)</span></h1>
  <div class = "container">
    <div class = "between_weathwe">
    <%= weather_icon(@weather) %>
      <p class = "weather_font"><%= weather_japanese(@weather) %></p>
    </div>
    <div>
      <p class = "weather_top weather_font">体感気温：<%= @apparent_temperature.round %>℃</p>
      <p class = "weather_font">最高気温：<%= @temperature_high.round %>℃</p>
      <p class = "weather_font">最低気温：<%= @temperature_low.round %>℃</p>
      <p class = "weather_font">降水確率：<%= @rain_possibility.round %>%</p>
    </div>
  </div>
    <h4><span class = "under"><%= weather_description(@apparent_temperature) %></span></h4>
    <h2 class = "title">明日のTENKIHUKU一覧</h2>
    <% @pictures.each do |picture| %>
    <% current_pictures(@apparent_temperature) %>
      <% if current_user.gender == picture.user.gender && @current_temperature == picture.weather %>
      <div class="panel-body">
        <%= link_to image_tag(picture.image.url) ,picture_path(picture.id),class:"item" %>
        <br>
      </div>
      <% end %>
    <% end %>
  <%= paginate @pictures %>
  <br>
  <%= link_to 'TENKIHUKUを投稿する', new_picture_path, class:"button_while" %>
</div>