config/routes.rb
Rails.application.routes.draw do
  root 'tops#top'

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :following, :followers, :mypage, :favorite
    end
  end

  resources :pictures do
    collection do
      get :tomorrow_index
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TENKIHUKU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= link_to image_tag("/assets/logo.png"), root_path , class:"logo" %>
      <% if user_signed_in? %>
        <%= link_to "今日の天気", pictures_path, class:"square_btn" %>
        <%= link_to "投稿する", new_picture_path, class:"square_btn" %>
        <%= link_to "マイページ", mypage_user_path(current_user), class:"square_btn" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"square_btn" %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class:"square_btn" %>
        <%= link_to "ログイン", new_user_session_path, class:"square_btn" %>
      <% end %>
    </header>
    <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
  <footer>
    <%= link_to image_tag("/assets/logo.png"), root_path %>
    <p>© 2015-2018 Copyright Yoppi Corp.</p>
  </footer>
</html>